# Use postgres/example user/password credentials
version: '3.1'

services:
  snelf-postgres:
    image: postgres:14-alpine
    restart: always
    container_name: snelf-postgres
    environment:
      POSTGRES_DB: testejp
      POSTGRES_USER: testejp
      POSTGRES_PASSWORD: testejp
    ports:
      - 54320:5432
    volumes:
      - ./init-scripts/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - snelf-data:/var/lib/postgresql/data

  snelf-back:
    build: ./snelf_backend
    container_name: snelf-back
    environment:
      - DB_SERVER=snelf-postgres
      - POSTGRES_DB=testejp
      - POSTGRES_USER=testejp
      - POSTGRES_PASSWORD=testejp
    volumes:
      - ./snelf_backend:/back_app
    ports:
      - 8001:8000
    depends_on:
      - snelf-postgres

  fasttext:
    build: ./snelf_backend/_model
    container_name: fasttext
    volumes:
      - ./:/fasttext

  snelf-front:
    build: ./snelf_frontend
    container_name: snelf-front
    stdin_open: true
    # Mount our host directory to the docker container
    # Mount (.) current directory to the docker container code/snelf-frontend
    # Reflect file changes from host to container
    volumes:
      - ./snelf_frontend:/front_app
      - /front_app/node_modules
    ports:
      - 3001:3000
    depends_on:
      - snelf-back
    command: npm run start
    environment:
      - DOCKER_CLIENT_TIMEOUT=120
      - COMPOSE_HTTP_TIMEOUT=120


volumes:
  snelf-data:
  
 #networks:
 #   default:
 #    name: snelf-network